<!DOCTYPE html>
<html lang="tr-TR">
    <head>
<meta http-equiv="Content-Type" content="text/html charset=utf-8">
<meta http-equiv="Content-Language" content="tr">
<meta charset="utf-8">
<title>PHP EĞİTİM</title>
<style>

</style>    
</head>
<body style="background-color: black; color:aliceblue ">

<form action="02ILETISIMFORMUSONUCUYGULAMASI.PHP" method="post" >

<table width="500"  cellpadding="0" cellspacing="0">

<tr>
    <td width="150">Adiniz Soyadiniz</td>
    <td width="20">:</td>
    <td width="330"><input type="text " name="adisoyadi"></td>
</tr>
<tr>
    <td width="150">Telefon Numaraniz</td>
    <td width="20">:</td>
    <td width="330"><input type="text " name="telefon"></td>
</tr>
<tr>
    <td width="150">E-mail Adresiniz</td>
    <td width="20">:</td>
    <td width="330"><input type="email " name="emailadresi"></td>
</tr>
<tr>
    <td width="150">Konu</td>
    <td width="20">:</td>
    <td width="330"><input type="text " name="konusu"></td>
</tr>
<tr>
    <td width="150">Mesaj</td>
    <td width="20">:</td>
    <td width="330"><textarea name="mesaj"></textarea></td>
</tr>
<tr>
    <td width="150">&nbsp;</td>
    <td width="20">&nbsp;</td>
    <td width="330"><input type="submit" value="Gonder"></td>
</tr>




</table>
</form>








<script>

</script>

<?php 























?>



</body>




</html>